use_frameworks!

target 'VOInteractiveLabel_Example' do
  pod 'VOInteractiveLabel', :path => '../'

  target 'VOInteractiveLabel_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
